---
title: A theoretical derivation of the aggregate supply curve, accounting for farm entry and exit
# author: "Benjamin Schiek"
# date: "`r Sys.Date()`"
abstract: |
  The functional form of aggregate supply is typically specified in order to facilitate calculations, with little thought given to its theoretical basis. This results in theoretical contradictions which call into question the results of the analysis. Here we derive a closed form aggregate agricultural supply and demand functions from microeconomic axioms and the assumption of lognormally distributed yields. The resulting functional form is highly instructive and agrees well with other aspects of theory... indicates that farm market participation is proportionate to the probability that the producer harvest price will be greater than the farm population's mean marginal cost of production. Allows for analysis of price and technology impacts at specific centiles. The elasticity The functional form opens a new vista on supply elasticity...decomposed into yield and farm participation terms. An aggregate farm input demand curve is also derived, followed by an aggregate farm commodity demand curve. The supply curve is fit to Kenya maize data. Food policy implications are discussed.

header-includes:
  - \usepackage{geometry}
  - \geometry{top=1in,left=1in,bottom=1in,right=1in}
  - \usepackage{framed}
  - \usepackage{setspace}\doublespacing
  - \usepackage{float}
  - \floatplacement{figure}{H}
  - \usepackage{amsmath}
  - m_umberwithin{equation}{section}


output:
  pdf_document:
   fig_caption: true
   number_sections: true
   #latex_engine: xelatex
# mainfont: Times Roman

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Introduction

In ex-ante impact assessments of exogenous changes in agricultural technology and agroclimatic conditions, aggregate supply curves are often specified primarily for the purpose of facilitating certain calculations (usually of economic surplus, deadweight loss, and the like), with secondary consideration given to the plausibility of the theoretical underpinnings implied by the choice of functional form. The resulting models are then, by construction, theoretically opaque.

In particular, it is unclear whether they are consistent with microeconomic principles regarding homogeneity, convexity/concavity, and profit maximization; and it is unclear what shape of farm production density function is implied by the model. That is to say, if aggregate supply $Q$ may be defined as the definite integral of farm production function $q^*$ times the production density $\rho(q^*)$ over the domain of profitable production $(\underline{q}^*, \bar{q}^*)$,

\begin{equation}
Q(P) = \int_{\underline{q}^*}^{\bar{q}^*} q^* \rho(q^*) \: dq^*
\label{eq:sup1}
\end{equation}

then it is not readily apparent from expedient specifications of $Q$ what the functions $q^*$ and $\rho(q^*)$ are, nor whether they are plausible vis-a-vis microeconomic theory and empirical evidence. Critically, expedient specifications of $Q$ also gloss over farm entry and exit---i.e. the domain of profitable production $(\underline{q}^*, \bar{q}^*)$---such that it is not possible to decompose changes in aggregate supply into yield and area or employment (farm entry/exit) components.

The parameterization of expedient specifications also tends to be highly abstract, with no clear mapping to the relevant measurable, real world phenomena---i.e. technology, input prices, agroclimatic conditions, demographic variables, etc. This leaves very little basis upon which to assess the plausibility of different parameterizations of a given exogenous shock, or to attribute modeled impacts to the exogenous shock with confidence (the attribution problem) [mention attrib prob here with refs if going short form]. Some expedient forms also introduce awkward artifacts---such as the possibility of negative supply quantities and/or of farms producing for free, in the case of the linear aggregate supply curve---which further limit or complicate the model's explanatory power. [add extra bit about local approximation if going short form]
<!-- [, while adding more layers of methodological wrangling/theoretical opacity.] -->
<!-- [which in turn invites misuse and abuse of the model, and otherwise complicates the defense of any modeling results.] -->
<!-- [the mathematical expression no different from the same statement in literary form] -->
<!-- [Meanwhile, the growing disparity between current research funding levels and the levels that would seem to be justified by expediently specified ex-ante impact assessments suggests that donors have stopped taking the results of such models seriously...] -->

To be fair, this is, in some sense, the whole point of expedient specifications of aggregate supply and demand: A degree of explanatory power is deliberately sacrificed in exchange for computational expedience. And, judging by the thousands of published ex-ante impact assessments of agricultural research that specify linear aggregate supply and demand functions, the modicum of explanatory power retained by such specifications appears, prima facie, to be sufficient for most modeling purposes. However, the mere number of publications may be a misleading indicator of sufficiency. It may reflect, rather, the computational ease of the model, and/or the absence of viable alternatives. Levels of funding for agricultural research have steadily declined from what would be justified by such assessments, indicating that many donors have stopped believing them [@hurley2014re; @hurley2016returns].  This indicates increasingly insufficient ...in terms of providing credible impact assessments.

There is thus a demand for transparent models...

Here we derive an aggregate supply curve from the following Axioms:

1) Diminishing marginal returns

2) Farms maximize their expected net benefit subject to a budget constraint (also known as cost-minimization)

3) Supply curves slope upwards

4) Demand curves slope downwards

5) Farms enter production only if it increases their expected net benefit

6) Farm production is lognormally distributed

The derived curve explicitly accounts for farm entry/exit, such that supply response to shocks can be decomposed into yield and area components. The parameters of the curve have a straightforward interpretation in terms of concrete, measurable phenomena, such that exogenous shocks may be modeled precisely and transparently.

At the end of the derivation, we walk through an illustrative application of the derived curve based on Kenya maize farm data.



-Agrees with Lipton's adoption criterion

-all parameters have a clear interpretation in terms of concrete, measurable vars

-Can examine questions of employment, tech induced shift,...

-elasticity decomposed into employment and tech components

-result: axioms 1+2 -> production is undefined at h=1, constant returns to scale not possible. axioms 1+2+3 -> only decreasing returns to scale possible.

-sketch out extension to aggregate demand curves and PE analysis




...expedient forms are considered unavoidable because...characterize the alternative, a theoretical derivation, as an impossible task [a fool's errand?]...
 

In the name of expedience, then, many methodological headaches are accumulated. At some point the headaches outweigh the expedience   Difficult to defend and impossible to account for farm entry and exit. disentangle impact from model artifact...difficult to tell whether the result is due to exogenous shock, or to artifacts of the model  ...


One is free to argue that the expedient approach is not intended to be so rigorous... for purposes of stakeholder discussions don't need to get so complex...Well, just saw above how the pursuit of expedience quickly lands the modeler in a great deal of methodological complexity. And This is at odds with the available evidence. After decades of exorbitant ex-ante impact assessments, there is evidence that donors have stopped believing them (references in Literature review below). And this correlates with a global decline in funding for agricultural research. There is a market out there unmet demand out there for transparent modeling, both by stakeholders interested in a clearer picture of potential impacts, and by modelers frustrated with the theoretical opacity of current methods.

focus on the aggregate supply curve...although the 
aim here is to replace theoretical opacity with transparency...introduce a model where model results can be traced back to concrete variables and axioms, and not to modeler fiat.











The resulting form accounts for farm entry and exit...transparent mapping between parameters and concrete real world variables... proportional to probability that price will remain above ...

-if somewhere along the way there are corollaries which seem wrong, the offending corollary can be traced back to specific axioms, as opposed to a shrug of the shoulders.

-here we derive an aggregate supply curve from 6 Axioms... First, the farm production derived from Axioms 1-4. Then the aggregate curve follows from introducing Axioms 5-6.

benefits of derived aggregate supply curve:


-illustrative application using Kenya maize data



-----------------------------------


# Literature review

In 1944, Von Neumann and Morgenstern observed that "part of the feeling of dissatisfaction with the mathematical treatment of economic theory derives largely from the fact that frequently one is offered not proofs but mere assertions which are really no better than the same assertions given in literary form" [@morgenstern1953theory]. The authors go on to suggest there is a "scientifically unsound" inclination among economists to confuse these formalized literary assertions, including "very valuable surmises and inspiring anticipations of results", with proofs or otherwise rigorously derived theoretical results [@morgenstern1953theory]. More recently, Romer has similarly criticized the rise of "mathiness" in economic modeling.
<!-- "There is no point in using exact methods where there is no clarity in the concepts and issues to which they are to be applied" [@morgenstern1953theory]. -->
<!-- "the economic problems were not formulated clearly and are often stated in such vague terms as to make mathematical treatment _a priori_ appear hopeless because it is quite uncertain what the problems really are" [@morgenstern1953theory]. -->

"[The style that I am calling mathiness lets academic politics masquerade as science.] Like mathematical theory, mathiness uses a mixture of words and symbols, but instead of making tight links, it leaves ample room for slippage between statements in the languages of words as opposed to symbols[, and between statements with theoretical as opposed to empirical content]". [@romer2015mathiness]

The slippage ... to confuse results with assumptions (petitio principii), or, as in the case of the economic surplus model, to infuse a collection of contradictory and/or unfounded assertions with an air of rigor and coherence.

Specification of the aggregate supply curve may be considered a case in point. The model is not theoretically derived, but rather a collection of educated guesses or surmises translated into mathematical equations. Many of these surmises imply well documented contradictions of basic economic theory, and/or inconvenient ramifications vis-a-vis the supposed benefits of research and technology adoption []. The model has evolved into its present form not by force of logic, but as a matter of preference. For example, there was considerable debate in the 1970s over whether the research-induced supply curve shift should be modeled as a parallel shift or a pivot [@alston1995science; @norton1981evaluating; @lindner1978supply]. The debate was further complicated by differing views as to whether supply should be modeled as a linear or a curved function. Without a theoretical framework to link parameter values and functional forms to real world conditions, the debate was ultimately inconclusive. The answers to the questions left unresolved by the debate have come down to us today as a matter of preference. In their highly influential book, _Science Under Scarcity_, Alston et al. indicated their preference for the linear parallel shift [-@alston1995science]. This is a conspicuous choice, to put it mildly, considering that 1) it prefigures research impacts in the best possible light, and 2) by the authors' own admission, there are no theoretical or empirical grounds to justify this preference [@alston1995science; @alston2009economics]. AR4D partial equilibrium impact studies since then have generally follow suit.

...The current sense is that this is somehow impossible. The verdict:

"What does economic theory tell us about the nature of these shifts? Unfortunately, not very much. To be confident about this aspect of the problem would require either (a) precise econometric evidence or (b) detailed information on the effects on individual agents, details of industry structure including details on exit and entry of firms, and a complete theory of aggregation. This information is not available; assumptions are unavoidable" (Alston, Norton, & Pardey, 1995).

In this article, we effectively provide (b)..."effects on individual agents" is a matter of farm level modeling, and "industry structure including details on exit and entry of firms" is a matter of Axiom 5.  show that economic theory can tell us a great deal more than these guys suspected...an optimistic view of what theory can tell us about the aggregate supply response to exogenous shocks.


Expedient functional forms also tend to introduce awkward model artifacts---such as the possibility of negative supply quantities and/or of farms producing for free, in the case of linear supply functions---which effectively reduce the form to a local approximation of some inscrutable global function, with validity restricted to a small domain of convergence around the starting equilibrium point. The 
The representation of exogenous shocks in terms of such abstract parameters is thus largely a matter of modeler fiat. Insofar as the modeling results hinge upon this parameterization, they too are prefigured by modeler fiat. The impact "assessment" is thus more accurately an impact _assertion_ dressed up in mathematical language, i.e. in this measure, reduced to an exercise in petitio principii.
<!-- -contradict theory [have to be constant returns to scale but also upward sloping demand curves...] -->

...haven't even gotten to adoption yet...
This, in turn, complicates the defense of modeling results. Without any theoretical framework by which to map the real world to model parameters, the parameterization of exogenous shocks effectively defaults to modeler fiat.  That is, the "assessment" is reduced to an _assertion_ dressed up in mathematical symbols. The     cannot be decomposed into specific components---a technology effect versus a price effect---
...distinguish between impact, model artifact, modeler fiat.
, and cannot be decomposed into technology and price components. 

When there is a [...Wd be nice to consider a range of scenarios covering a range of potential input price increases versus technology shocks, but this not possible ... not clear why adoption rate takes a certain value... or how the shock affects the entry and exit of farms... nor how the shock affects the aggregate...  nor which centiles adopt...] The representation of exogenous shocks to real world parameters in terms of model parameters thus largely boils down to a matter of modeler fiat. Insofar as modeling results hinge upon the parameterization of shocks, the conclusions of the impact assessment are, in this measure, also by fiat; and the whole process is thereby reduced to an exercise in petitio principii. This obviously complicates subsequent defense of the modeling results, especially if the modelers and/or their source of funding have a vested interest in the results.

[The response to the growing impatience is the cosmetic approach---MIRR]





The constant elasticity of supply curve, for example,

\begin{equation}
Q = a P^{\eta}
\end{equation}

conflates yield and employment response to price changes in one parameter, $\eta$.

Expedient specifications also tend to introduce awkward model artifacts. The parameter $\eta$, for example, implies that yield and employment responses offset each other such that $\eta$ is always constant. The linear aggregate supply curve, on the other hand, implies the possibility of negative supply quantities and/or of farms producing for free. This either requires redefinition of the curve as a piecewise function---which further complicates interpretation in terms of Equation \ref{eq:sup1}---or compels us to regard the function as a local approximation to an inscrutable global function, with validity restricted to a small domain of convergence around the starting equilibrium point.

Finally, the parameterization of such forms tends to be highly abstract, with no clear mapping to the relevant measurable, real world phenomena---i.e. technology, input prices, agroclimatic conditions, demographic variables, and so on. This leaves very little basis upon which to assess the plausibility of a given parameterization of exogenous shocks. How should a 10% increase in total factor productivity be represented in terms of a change in, say, $a$ and $\eta$? The answer effectively boils down to modeler fiat, which in turn invites misuse and abuse of the model, and otherwise complicates the defense of any modeling results.

<!-- You have to ask what sort of farm production fn and density function result in a linear form for the aggregate curve... -->
<!-- It is still customary to specify a linear aggregate supply curve, for example, with no discussion of the highly unlikely shape of the farm production density function that is implied by that functional form. That is to say, if the aggregate supply $Q$ of a farm population with production function $q$ and production density $\rho(q)$ may be defined -->

<!-- \begin{equation} -->
<!-- Q = \int_{\underline{q}}^{\bar{q}} q \rho(q) \: dq -->
<!-- \end{equation} -->

<!-- Then a linear aggregate supply curve implies a uniform distribution of $q$. Empirically speaking, one may say without controversy that farm production density is never uniform, but rather tapers off to zero at low and high values of $q$, resulting in a bell or skewed bell shaped function. -->

<!-- aware of market entry and exit, which in turn implies the truncation $\underline{q},\: \bar{q}$---but from above or below, or both? -->

<!-- The elasticity of  -->

<!-- \begin{equation} -->
<!-- \frac{\partial \ln(Q)}{\partial \ln(P)} Q = \frac{P}{Q} c -->
<!-- \end{equation} -->

# Derivation of the yield function from Axiom 1 (diminishing marginal returns)

Throughout much of written history, astute observers have noticed that the usefulness of increments in the quantity of a good is inversely proportional to amount of the input or good or service already acquired [@kauder1953genesis]. In 1738, Daniel Bernoulli put it this way:
<!-- an input (in the case of producer yield functions) or good or service (in the case of consumer utility functions) -->

>\singlespacing "In the absence of the unusual, the utility resulting from any small increase in wealth will be inversely proportionate to the quantity of goods previously possessed" [@bernoulli1954exposition].

\doublespacing

Today, this is known as the "law of diminishing marginal returns".

\begin{framed}
   \textbf{Axiom 1} \\ The law of diminishing marginal returns.
\end{framed}

Formalization of Bernoulli's verbal statement of the law of diminishing marginal returns depends upon how one defines "small increase". If "small increase" means a marginal increase, then Bernoulli's statement can be written down as follows.^[Bernoulli himself could not have had "marginal increase" in mind per se, as calculus had not yet been invented.]

\begin{equation}
\frac{\partial \ln(y)}{\partial x} \sim \frac{1}{x}
\label{eq:dimUtilDefine}
\end{equation}

Where, to be clear, the term $\partial \ln(y) / \partial x$ is the percentage change in utility given a marginal increase in the quantity of good $x$, and "$\sim 1 / x$", means "inversely proportionate to the quantity of good $x$ already acquired". An expression $y(x)$ for the yield of good $x$ can then be obtained by integrating Bernoulli's statement.

\begin{equation}
\begin{split}
\int \frac{\partial \ln(y)}{\partial x} \: dx &= \int \alpha \frac{d \ln(x)}{dx} \: dx \\
\ln(y(x))  &= \alpha \ln(x) + k \\
y(x) &= e^k x^{\alpha}
\end{split}
\label{eq:integrate_lny}
\end{equation}

Where the proportionality constant $\alpha = \partial \ln(y)/ \partial \ln(x)$ is the input elasticity of yield, i.e., the percentage change in yield given a $1$ percent increase in input $x$.

In the multivariate case, an expression $y(\mathbf{x})$ for yield as a function of a vector of $n$ goods $\mathbf{x} = [x_1,x_2,...,x_n]$ can be obtained as follows.

\begin{equation}
\int \nabla_{\mathbf{x}} \ln(y) \cdot d \mathbf{x} = \int D(\boldsymbol{\alpha}) \nabla_{\mathbf{x}} \ln(\mathbf{x}) \cdot d \mathbf{x}
\end{equation}

\begin{equation}
\begin{split}
\ln(y(\mathbf{x})) &= \boldsymbol{\alpha} \cdot \ln(\mathbf{x}) + \alpha_0 \\
y &= e^{\alpha_0} \prod_{i = 1}^{n} x_i^{\alpha_i}
\end{split}
\label{eq:cobbDoug}
\end{equation}

where $\boldsymbol{\alpha}$ is the vector of input elasticities corresponding to each $x_i$, the notation $D(\boldsymbol{\alpha})$ indicates a diagonal matrix with the elements of $\boldsymbol{\alpha}$ along its diagonal, and

\begin{equation}
\nabla_{\mathbf{x}} \ln(y) = \left[ \begin{matrix} \frac{\partial \ln(y)}{\partial x_1} \\
\frac{\partial \ln(y)}{\partial x_2} \\
\vdots \\
\frac{\partial \ln(y)}{\partial x_n}
\end{matrix} \right]
\end{equation}

It is straightforward to see that equation \ref{eq:cobbDoug2} is a homogeneous function with degree of homogeneity $h$ equal to $\sum_i \alpha_i$, and is thus also homothetic. It is also straightforward to demonstrate monotonicity and concavity. There is no need, then, to impose these as additional assumptions. They follow from the assumption of diminishing marginal returns.

In an actual analysis, exogenously given control variables ($k_i$) are usually included in the model. These typically include demographic variables such as age, education, gender, household size, as well as agroclimatic variables such as temperature, rainfall, soil conditions, and so forth. (Analysis is said to be "ceteris paribus" when these variables are held constant at a particular value across the population.) Equation \ref{eq:cobbDoug} is thus henceforth rewritten as follows.

\begin{equation}
y = g_0 \prod_{i = 1}^{n_k} k_i^{\kappa_i} \prod_{i = 1}^{n_x} x_i^{\alpha_i} \:\:;\:\:\: g_0 = e^{\alpha_0}
\label{eq:cobbDoug2}
\end{equation}

Where the $\kappa_i$ are the control variable elasticities of yield. These are non-discretionary and may thus take positive or negative values. The input elasticities $\alpha_i$, on the other hand, which correspond to discretionary management variables, are generally positive. However, there may arise cases where a variable does not fall neatly into either the management or control category. In the empirical analysis presented farther below, for example, the coefficient on child family labor takes a negative value. Labor is generally considered a discretionary management variable; but family labor, and especially child family labor, might, in some cases, better be considered a control variable, indicative of hard constraints beyond the farmers' discretion. For purposes of economic analysis, the degree of homogeneity is calculated only over the production elasticities corresponding to management variables ($h = \sum_i \alpha_i$, omitting the $\kappa_i$).

Interpretation of the constant $g_0$ is as difficult as we want to make it. It is usually called the total factor productivity, and understood to represent the yield per unit "all inputs"---although a more accurate description would be yield per unit "all input and control variables, raised to various powers". For those not yet comfortable working in units of, say,

$$
kgs. \: acres^{-1} \: liters^{-\alpha_{pest}} \: kgs.^{-\alpha_{fert}} \: manhours^{-\alpha_{labor}} \: mm.^{-\alpha_{rain}}\: degrees^{-\alpha_{temp}} \: years^{-\alpha_{age}} \: num. \: people^{-\alpha_{HHsize}}
$$
an alternative approach is to arbitrarily define $g_0$ in terms of another parameter that is expressed in intelligible units, and to work with this instead. For example, $g_0$ may be defined in terms of another parameter $y_0$ and fixed reference values $\tilde{k}_i$, $\tilde{x}_i$ that have the same units as the corresponding management and control variables $x_i$ and $k_i$.

\begin{equation}
g_0 = y_0 \prod_{i = 1}^{n_k} \tilde{k}_i^{-\kappa_i} \prod_{i = 1}^{n_x} \tilde{x}_i^{-\alpha_i}
\end{equation}

Such that the yield function may be rewritten

\begin{equation}
y = y_0 \prod_{i = 1}^{n_k} \left( \frac{k_i}{\tilde{k}_i} \right)^{\kappa_i} \prod_{i = 1}^{n_x} \left( \frac{x_i}{\tilde{x}_i} \right)^{\alpha_i}
\label{eq:cobbDoug3}
\end{equation}

Because the terms in parentheses are dimensionless, $y_0$ must have the same units as $y$; and $y_0$ may be interpreted as the value of $y$ when all management and control variables equal their reference values. In the empirical study included here, for example, the reference values are set equal to the sample means, such that $y_0$ is the value of $y$ evaluated at the sample means of the input and control variables.

Equation \ref{eq:cobbDoug3} is, of course, the Cobb-Douglas form. Outside of Economics, it would simply be referred to as a (multivariate) power law. Such forms are often good models of observed processes across a wide range of research contexts and disciplines. In Economics, the Cobb-Douglas form was widely used from the 1920s to 1950s on the basis of its good empirical fit, but fell into disrepute thereafter for its perceived lack a theoretical basis. Capalbo and Antle [-@capalbo2015agricultural] offer a succinct introduction to this vast discussion. The forgoing derivation of the Cobb-Douglas form from Axiom 1 in some measure redresses the lack of a theoretical basis. Other perceived shortcomings of the form are addressed in the Discussion.
<!-- In equation \ref{eq:cobbDoug2}, the shorthand $y_0 = e^{\alpha_0}$ has also been introduced. The scale factor $y_0$ is the yield when inputs $\mathbf{x}$ are set to 1 and the control variables $\mathbf{k}$ are also set to 1. It may thus be interpreted as the "unit input yield" or "unit input ceteris paribus yield", to be more precise. "Basal yield" is henceforth used as a shorthand. -->
<!-- Many economists prefer to call $y_0$ the "total factor productivity" (TFP). This is because $y_0$ equals, in some sense, the "yield per unit all inputs" when it is isolated on one side of the equation. However, the presence of control variables complicates this interpretation. Moreover, TFP implies bizarre and rather useless units of measurement. For example, if the inputs $x_i$ are labor and pesticide, while the control variables $k_i$ are rainfall, temperature, and farmer age, then the TFP $y_0$ has units of kg hectare$^{-1}$ manhour$^{-1}$ liter$^{-1}$ millimeter$^{-1}$ degree Celsius$^{-1}$ years$^{-1}$, each of which is raised to various exponents (the respective elasticities $\alpha_i$ and $\kappa_i$). Because of the exponents, a more accurate name for TFP would be the "technology adjusted total factor productivity". -->
<!-- Nonetheless, a very mature literature has developed around TFP, and the reader is encouraged to continue thinking of $y_0$ in terms of TFP if that is what they are most comfortable with. The "basal yield" interpretation is merely provided here as an alternative for those of us who wrestle with the idea of TFP or are not yet familiar with it. -->
<!-- exogenously given control variables like age, soil quality, or climate variables. -->
<!-- TFP vis-à-vis dimensional analysis -->
<!-- The (in)famous residual -->
<!-- “The rate of growth of total factor productivity is defined as the difference between the rate of growth of real product and the rate of growth of real factor input” (Jorgenson & Griliches, 1967). This definition violates dimensional analysis. -->
<!-- Given a yield function -->
<!-- y=Kx_1^(α_1 ) x_2^(α_2 )…x_n^(α_n )	(1) -->
<!-- "TFP"=K=y/(x_1^(α_1 ) x_2^(α_2 )…x_n^(α_n ) )	(2) -->
<!-- There are two problems with this expression from the point of view of dimensional analysis. First of all, the units in which “TFP” is expressed are impossible to make sense of. Say n=4, with x_1 standing for labor, x_2 for machinery, x_3 for fertilizer, and x_4 for pesticide. Then TFP has units of production per unit -->
<!-- area (man hour)^(α_1 ) (machine hour)^(α_2 )  (weight)^(α_3 )  (volume)^(α_4 )	(3) -->
<!-- The second, more serious, problem is that these units will always vary from one data set to another. Even if the variables x_1,x_2,…,x_n are the same across studies, and are expressed in the same units, the units in which the “residual” K is expressed will nonetheless vary because the estimated parameters α_i vary. It is therefore impossible to make meaningful comparisons of K across data sets. -->
<!-- On the other hand, it is possible to make meaningful comparisons of the residual in another sense. Define the parameter K as follows: -->
<!-- K=k/(x ̃_1^(α_1 ) x ̃_2^(α_2 )…x ̃_n^(α_n ) )	(3) -->
<!-- Where the x ̃_i are arbitrarily chosen reference values. Then the yield equation becomes: -->
<!-- y=ku_1^(α_1 ) u_2^(α_2 )… u_n^(α_n )  ;  u_i=x_i/x ̃_i 	(3) -->
<!-- It now becomes clear what the units of k are. Each x ̃_i has the same units as its respective x_i. This means that all of the u_i^(α_i ) terms on the right hand side of the equation are dimensionless. Therefore, the units of k must agree with the units of whatever is on the left hand side, which happens to be yield.  -->
<!-- k=y/(u_1^(α_1 ) u_2^(α_2 )… u_n^(α_n ) )	(5) -->
<!-- When interpreted in this way, it is now possible to make meaningful comparisons of the residual across data sets (if the reference values x ̃_i are harmonized across the data sets). However, the residual now has units of productivity with respect to land only, and not with respect to any other factor, much less the “total factor”. -->
<!-- Conclusion -->
<!-- Above I have shown that TFP (equation 2) is measured in units which 1) are virtually impossible to make sense of, and 2) cannot be compared across data sets. I have shown that it is possible to express the residual in straightforward units that are comparable across data sets, but that these are units of land productivity only. The residual may be interpreted as TFP only at the cost of nonsensical units and cross-study incompatibility. A residual with sensible units and comparability, on the other hand, comes at the cost of expressibility only in units of a single factor’s productivity—land in the case of farms, widget factories in the case of firms. -->
<!-- As mentioned above, this result depends on a definition of small increase as a marginal increase. Other forms result from other definitions of small increase. If small increase is defined as a percentage increase, for example, a functional form involving Lambert's W function results (left as an exercise for the reader). The Cobb-Douglas function is selected from among these two choices on empirical grounds. (The Cobb-Douglas function is famous for how well it fits economic data across many contexts and scales.) -->

# Derivation of the yield envelope from Axiom 2 (net benefit maximization)

...pardon the remedial...


Equation \ref{eq:cobbDoug2} captures yield response to inputs and control variables in accordance with Axiom 1, the law of diminishing marginal returns.

The next step in the theoretical derivation of the partial equilibrium model is based on the assumption that farmers want to maximize their net benefit subject to a budget constraint. (Consumers and firms on the demand side are assumed to be similarly motivated, but the present section focuses on the supply side.)

\begin{framed}
   \textbf{Axiom 2} \\ Farms, as well as firms and consumers on the demand side, maximize their net benefit subject to a budget constraint.
\end{framed}

Axiom 2 implies that farmers apply inputs such that revenue is maximized, given a budget constraint. The problem of finding the optimal input quantities that achieve this goal can be formalized as follows.

\begin{equation}
\max_{\mathbf{x}} Py \:\:\: s.t. \:\:\: C \leq B
\end{equation}

where $P$ is the output price, $B$ is the farmer's budget, $C$ is the cost function, defined

\begin{equation}
C = \mathbf{w} \cdot \mathbf{x}
\end{equation}

and $\mathbf{w}$ is the vector of input prices corresponding to each input in $\mathbf{x}$.

The Lagrangian is then

\begin{equation}
\mathcal{L} = Py - \lambda (C - B)
\end{equation}

Where $\lambda$ is the farm budget shadow price, that is, the marginal benefit to the farm of a marginal increase in budget.

\begin{equation}
\frac{\partial \mathcal{L}}{\partial B} = \lambda
\end{equation}

The first order conditions for a maximum work out to:

\begin{equation}
\nabla_{\mathbf{x}} \mathcal{L} = Py D(\mathbf{x})^{-1} \boldsymbol{\alpha} - \lambda \mathbf{x} = \mathbf{0}
\label{eq:eqFOC}
\end{equation}

Where the $\mathbf{0}$ indicates a vector of zeroes equal to the length of $\mathbf{x}$. This is then solved for the optimal input levels $\mathbf{x}^*$.

\begin{equation}
\mathbf{x}^* = P y^* / \lambda D(\mathbf{w})^{-1} \boldsymbol{\alpha}
\end{equation}

Or, alternatively,

\begin{equation}
x_v^* = \frac{P y^* \alpha_v}{\lambda w_v}
\label{eq:inputDem1}
\end{equation}

The optimal yield, or yield envelope, or economic yield, $y^*$ is then found by evaluating $y$ at $\mathbf{x}^*$.

\begin{equation}
y^* = y(\mathbf{x}^*; y_0, \boldsymbol{\alpha}, \mathbf{k}, \boldsymbol{\kappa}) = y_0 \prod_i \left(\frac{P y^* \alpha_i}{\lambda w_i} \right)^{\alpha_i} \prod_i k_i^{\kappa_i}
\end{equation}

Taking logs and factoring out $\ln (P y^*/\lambda)$,

\begin{equation}
\ln(y^*) = \alpha_0 + \ln \left(\frac{P y^*}{\lambda} \right) \sum_i \alpha_i + \sum_i \alpha_i \ln \left(\frac{\alpha_i}{w_i} \right) + \sum_i \kappa_i \ln(k_i) 
\end{equation}

But note that, by Euler's homogenous function theorem,

\begin{equation}
\sum_i \alpha_i = h
\end{equation}

where $h$ is the degree of homogeneity of $y$. Hence the previous equation can be rewritten

\begin{equation}
\ln(y^*) = \alpha_0 + h \ln \left(\frac{P y^*}{\lambda} \right) + \sum_i \alpha_i \ln \left(\frac{\alpha_i}{w_i} \right) + \sum_i \kappa_i \ln(k_i) 
\label{eq:eulerInvokd}
\end{equation}

Solving for $\ln(y^*)$,

\begin{equation}
\ln(y^*) = \frac{1}{1 - h} \left(\alpha_0 + h \ln \left(\frac{P}{\lambda} \right) + \sum_i \alpha_i \ln \left(\frac{\alpha_i}{w_i} \right) + \sum_i \kappa_i \ln(k_i) \right)
\end{equation}

And taking the exponential function of this then gives the yield envelope.

\begin{equation}
y^* =  \left(y_0 \left(\frac{P}{\lambda}\right)^h \prod_i \left(\frac{\alpha_i}{w_i}\right)^{\alpha_i} \prod_i k_i^{\kappa_i} \right)^{\frac{1}{1 - h}}
\label{eq:YdEnv1}
\end{equation}

Economic yield is thus a function of:

1) Input prices $\mathbf{w}$

2) The output price $P$

3) The input elasticities of yield $\boldsymbol{\alpha}$ (i.e. the technology)

4) The control variables $\mathbf{k}$

5) Their control variable elasticities of yield $\boldsymbol{\kappa}$

6) The farm budget shadow price $\lambda$

To reduce notational clutter, the yield envelope is henceforth rewritten as follows.

\begin{equation}
y^* = \left(y_0 \left(\frac{P}{\lambda} \right)^h \frac{\beta_x \beta_k}{\beta_w} \right)^{\frac{1}{1 - h}}
\label{eq:YdEnvCompact}
\end{equation}

Where the following shorthands have been introduced:
<!-- r &= \frac{P^h}{\beta_w} \:\:\:; \:\: \beta_w = \prod_i w_i^{\alpha_i} \\ -->

\begin{equation}
\begin{split}
\beta_w &= \prod_i {w_i}^{\alpha_i} \\
\beta_x &= \prod_i {\alpha_i}^{\alpha_i} \\
\beta_k &= \prod_i {k_i}^{\kappa_i}
\end{split}
\end{equation}

The steps followed above more or less align with the standard derivation of the Cobb-Douglas yield envelope found in textbooks (for e.g. Heathfield and Wibe [-@heathfield1987introduction]), with the important exception of the invocation of Euler's homogeneous function theorem in equation \ref{eq:eulerInvokd}.

The alternative form in terms of cost... the "yield-input isometry"

Note that the cost minimization problem gives the same result...

## The degree of homogeneity and output price elasticity of yield \label{sec:degHomog}

[The costStar^h  formulation of yield envelope]

[Put "certain useful elasticities/expressions" here maybe]

By invoking Euler's theorem in the derivation of the yield envelope above, the yield degree of homogeneity $h$ is made explicit in the yield envelope; and this lays bare some interesting critical properties. Note, first of all, that the yield envelope is undefined at $h = 1$. The theory constructed so far from Axioms 1 and 2 thus contradicts the deeply entrenched surmise among economists, going back at least to Hicks [-@hicks1963theory], and later cemented into place by Solow [-@solow1957technical], that yield functions are homogeneous of degree 1.

The appearance of $h$ in the yield envelope also offers an instructive expression for the output price elasticity of yield,

\begin{equation}
\frac{\partial \ln(y^*)}{\partial \ln(P)} = \frac{h}{1 - h}
\label{eq:PelastYstar}
\end{equation}

Here another Axiom comes into play.

\begin{framed}
   \textbf{Axiom 3} \\ Supply curves are positively sloped. $\left( \frac{\partial \ln(y^*)}{\partial \ln(P)} > 0 \right)$ \\
\end{framed}

From equation \ref{eq:PelastYstar}, it is clear that Axiom 3 imposes the following domain on $h$.

\begin{equation}
h \in (0, 1)
\end{equation}

Farms are thus limited to decreasing returns to scale, since increasing returns to scale ($h > 1$) imply a negatively sloped supply curve, in violation of Axiom 3, and since the yield envelope is undefined at constant returns to scale ($h = 1$).

In section \ref{sec:PDfunP}, circumstances are explored under which increasing returns to scale are possible. However, these circumstances generally apply to firms---mills and factories, for example---and not to farms.

The domain of $h$ derived above in turn implies the following bounds on the price elasticity of yield.

\begin{equation}
\frac{\partial \ln(y^*)}{\partial \ln(P)} \in (0, \infty)
\end{equation}
<!-- Note, in passing, that the input price elasticity of yield likewise bears the expected sign only under decreasing returns to scale. -->

<!-- \begin{equation} -->
<!-- \frac{\partial \ln(y^*)}{\partial \ln(w_i)} = \frac{-\alpha_v}{1 - h} -->
<!-- \end{equation} -->

<!-- With domain -->

<!-- \begin{equation} -->
<!-- \frac{\partial \ln(y^*)}{\partial \ln(w_v)} \in (-\infty, -\alpha_v) -->
<!-- \end{equation} -->

The yield envelope derived in equation \ref{eq:YdEnvCompact} implies that the farm supply curve^["Farm supply curve" is used as a shorthand for the "yield envelope as a function of price $P$, with all other variables held constant".] is a power law---or, in economics jargon, a constant elasticity of supply curve. This becomes more evident if the yield envelope is rewritten in the following compact form.

\begin{equation}
y^* = t_S P^{\eta(P, y^*)}
\end{equation}

Where

\begin{equation}
t_S = \left(y_0 \frac{\beta_x \beta_k}{\lambda^h \beta_w} \right)^{\frac{1}{1 - h}}
\end{equation}

And $\eta(P, y^*)$ is the price elasticity of yield defined in equation \ref{eq:PelastYstar}.

<!-- Both the scale parameter $t$ and exponent $\eta(P, y^*)$ depend critically upon the degree of homogeneity. -->
The output price elasticity of yield implies that the farm supply curve is elastic for $h \in (1 / 2 , 1)$, and inelastic for $h \in (0, 1 / 2)$, and linear with slope $t_S \bigr|_{h = 1 / 2}$ when $h = 1 / 2$.

This is important information. This means that (insofar as Axioms 1-3 are true) for a given increase in output price, the supply response in a population of farms with inefficient input elasticities (such that $h < 1 / 2$) will be less than proportionate to the increase in price. In a population of relatively input-efficient farms (such that $h > 1 / 2$), on the other hand, the supply response will be more than proportionate to the increase in price.

The farm supply curve approaches perfect inelasticity as $h$ approaches $0$, and approaches (but never reaches) perfect elasticity as $h$ approaches $1$. The scale factor $t_S$ approaches $0$ as $h$ approaches $0$, and tends toward infinity as $h$ approaches $1$.

## Input demand \label{sec:inDem}

Using equation \ref{eq:YdEnvCompact} to substitute for $y^*$ in input demand (equation \ref{eq:inputDem1}) gives the following expression for input demand as a function of basal yield, prices, input elasticities, the budget shadow price, and control variables together with their respective elasticities.

\begin{equation}
x_v^* = \frac{\alpha_v}{w_v} \left( y_0 \frac{P \beta_x \beta_k}{\lambda \beta_w} \right)^{\frac{1}{1 - h}}
\label{eq:inputDem2}
\end{equation}

Note that input demand, like optimal yield, is undefined at $h = 1$. The own price elasticity of input demand is

\begin{equation}
\begin{split}
\frac{\partial \ln(x_v^*)}{\partial \ln(w_v)} &= - 1 - \frac{1}{1 - h} \frac{\partial \ln(\beta_w)}{\partial \ln(w_v)} \\
&= \frac{-\alpha_v}{1 - h} - 1
\end{split}
\label{eq:ownPriceElas}
\end{equation}

Here another Axiom comes into play.

\begin{framed}
   \textbf{Axiom 4} \\ Demand curves are negatively sloped. $\left( \frac{\partial \ln(x_v^*)}{\partial \ln(w_v)} < 0 \:\: \forall v \right)$
\end{framed}

From equation \ref{eq:ownPriceElas}, it is clear that Axiom 4 imposes the following domain on $h$.

\begin{equation}
h \in (-\infty, 1 + \underline{\alpha}) \:\:; \:\:\: \underline{\alpha} = \min(\boldsymbol{\alpha})
\end{equation}

Considering that $\underline{\alpha} > 0$, the effective domain of $h$ satisfying both Axioms 3 and 4 (upward sloping supply curves and downward sloping demand curves) is

\begin{equation}
h \in (0, 1)
\end{equation}

The effective domain of $h$ in turn implies the following bounds on the own price elasticity of input demand.

\begin{equation}
\frac{\partial \ln(x_v^*)}{\partial \ln(w_v)} \in (\infty, -1)
\end{equation}

The input demand curve is thus always elastic, such that the increase in farm level demand resulting from a decrease in the input price is always more than proportionate to the fall in price.

Note that the cross price elasticity of input demand also bears the expected sign under the effective domain of $h$,

\begin{equation}
\frac{\partial \ln(x_v^*)}{\partial \ln(w_{j \neq v})} = \frac{-\alpha_j}{1 - h}
\label{eq:CrossPriceElas}
\end{equation}

As does the output price elasticity of input demand,

\begin{equation}
\frac{\partial \ln(x_v^*)}{\partial \ln(P)} = \frac{1}{1 - h}
\end{equation}

Equation \ref{eq:inputDem2} implies that the input demand curve^["Input demand curve" is used as a shorthand for the "optimal input level as a function of its price, with all other variables held constant".] is a power law. This is more evident when expressed in the following compact form.

\begin{equation}
x_v^* = z w_v^{\eta(w_v, x_v^*)}
\end{equation}

Where

\begin{equation}
z = \left(y_0 \frac{\beta_x \beta_k}{\lambda^h \tilde{\beta}_w} \right)^{\frac{1}{1 - h}} \:\:;\:\:\: \tilde{\beta}_w = w_v^{-\alpha_v}\beta_w
\end{equation}

And $\eta(w_v, x_v^*)$ is the own price elasticity of input demand, derived in equation \ref{eq:ownPriceElas}.

## Domains of the budget shadow price, economic yield, and input demand

Dotting the first order conditions (equations \ref{eq:eqFOC}) through by $\mathbf{x}$ and rearranging gives the following formula for the farm budget shadow price.

\begin{equation}
\lambda = \frac{P y^*}{C^*} h
\label{eq:lambdaHandy}
\end{equation}

That is, a farm's budget shadow price is equal to its revenue to cost ratio, scaled by the degree of homogeneity.

Assuming that farms only enter production if their expected revenue is greater than their cost (Axiom 5), then the following lower bound on $\lambda$ may be readily deduced.

\begin{equation}
\lambda > h
\label{eq:lamLoBound}
\end{equation}

\begin{framed}
   \textbf{Axiom 5} \\ Farms, as well as firms and consumers on the demand side, enter production only if their expected revenue is greater than their cost.
\end{framed}

This, in turn, implies the following upper bound on optimal yield.

\begin{equation}
y^* <  \left(y_0 \left(\frac{P}{h} \right)^h \frac{\beta_x \beta_k}{\beta_w} \right)^{\frac{1}{1 - h}}
\label{eq:ydUpBound}
\end{equation}

Note, in passing, that the notion of an upper bound on economic yields agrees with empirical observation [@herdt1988increasing; @pingali2001cereal]. In Pingali and Heisey's words:

>\singlespacing "The best yields obtained on experiment stations are often used as the indicator of technology potential. Experiment stations are often located on the best lands within a region and have reliable irrigation water supplies. Agronomic yield potential determined on experiment stations, with no physical, biological, or economic constraints, is the maximum achievable yield.... When the objective of the experiment is changed from maximizing yields to maximizing profits, the yields obtained by experiment station researchers drop significantly..." [-@pingali2001cereal].

\doublespacing
The lower bound on $\lambda$ likewise implies the following upper bound on input demand.

\begin{equation}
x_v^* < \frac{\alpha_v}{w_v} \left(y_0 \frac{P \beta_x \beta_k}{h \beta_w} \right)
\label{eq:inputUpBound}
\end{equation}

Recall that the upper bound on optimal expenditure is not derived but assumed as Axiom 5: $C^* < Py^*$.





## Marginal cost

From equation \ref{eq:cStar} it follows that the marginal cost of output is

\begin{equation}
\frac{\partial C^*}{\partial y^*} = \frac{P h}{\lambda} = \frac{C^*}{y^*}
\end{equation}

Under Axioms 1 and 2, then, the marginal cost of output is constant with respect to output. This agrees with empirical evidence [@lavoie2014post]. It also contradicts the theory of the firm presented in most microeconomic textbooks, which assumes (with no evidentiary basis) increasing marginal cost as output rises.

## The farm net benefit envelope

The optimized objective function or "net benefit envelope" $\mathcal{L}^*$ is just the objective function $\mathcal{L}$ evaluated at the optimal yield $y^*$.

\begin{equation}
\mathcal{L}^* = \mathcal{L} \bigr|_{y = y^*} = P y^* - \lambda (C^* - B)
\end{equation}

Note that, applying the handy relation in equation \ref{eq:lambdaHandy}, the net benefit envelope can be rewritten without the optimal expenditure term $C^*$.

\begin{equation}
\mathcal{L}^* = (1 - h) P y^* + \lambda B
\label{eq:NBenv}
\end{equation}









## Aggregate supply \label{sec:aggSupply}

Farm production $q^*$ is, of course, just farm yield envelope times farm area. If area is one of the control variables in the yield envelope, then $q^*$ is given by adding $1$ to the fitted exponent (call this $\kappa_a$) on area.

\begin{equation}
\begin{split}
q^* &= A y^* \\
&= y_0 \hat{\beta}^{\eta(D)} \left(\frac{E[P(T)]\bigr|_{t = 0}}{\lambda}\right)^{\eta(E[P(T)]\bigr|_{t = 0})}
\end{split}
\end{equation}

Where

\begin{equation}
\begin{split}
\hat{\beta} &= \frac{\beta_x \hat{\beta_k}}{\beta_w} \\
\hat{\beta_k} &= A \beta_k = A^{\kappa_a + 1} \prod_{i \neq a}^{n_k} k_i^{\kappa_i}
\end{split}
\end{equation}

And maximum economic production for given $A$, assuming farms only enter production if their expected revenue is greater than their cost (recall equation \ref{eq:ydUpBound}), is

\begin{equation}
\begin{split}
\bar{q}^* &= A \bar{y}^* \\
&= y_0 \hat{\beta}^{\eta(D)} \left(\frac{E[P(T)]\bigr|_{t = 0}}{h}\right)^{\eta(E[P(T)]\bigr|_{t = 0})}
\end{split}
\end{equation}

By definition, expected aggregate supply at or around the time of planting must be the definite integral of expected farm production over its density, from $0$ to maximum expected economic farm production $\bar{q}^*$.

\begin{equation}
Q_S = \int_{0}^{\bar{q}^*} q^* \rho(q^*) \: dq^*
\end{equation}

Where the farm density $\rho(q^*)$ function is defined such that

\begin{equation}
\rho(q^*) = \int_{0}^{\infty} \rho(q^*) \: dq^* = N_f
\end{equation}

Where $N_f$ is the number of farms in the population. The farm density may thus be rewritten in terms of a probability density function $f(q^*)$ as follows.

\begin{equation}
\rho(q^*) = N_f f(q^*)
\end{equation}

Supply can also of course be defined in terms of an integral of farm yield over its density.

\begin{equation}
Q_S = \int_{0}^{\bar{y}^*} y^* \rho(y^*) \: dq^*
\end{equation}

Where the yield density is defined such that

\begin{equation}
\rho(y^*) = \int_{0}^{\infty} \rho(y^*) \: dy^* = N_a
\end{equation}

Where $N_a$ is the number of acres (or whatever the unit of area is) in the population.

The latter expression may be more suitable when dealing with remote sensing data. The former is more suitable when dealing with farm survey data, as here.

\begin{equation}
\begin{split}
E[Q_S(T)]\bigr|_{t = 0} &= N_f \int_{0}^{\bar{q}^*} q^* f(q^*) \: dq^* \\
&= N_f y_0^{\eta(D)} E[\hat{\beta}^{\eta(D)}] E[P(T)]\bigr|_{t = 0}^{\eta(P)} \int_{0}^{h^{-\eta(P)}} \lambda^{-\eta(P)} f(q^*) \: dq^*
\end{split}
\label{eq:QSeq}
\end{equation}

By the law of the unconscious statistician, the integral in the expression above can be rewritten

\begin{equation}
\int_{0}^{h^{-\eta(P)}} \lambda^{-\eta(P)} f(q^*) \: dq^* = \int_{0}^{h^{-\eta(P)}} \lambda^{-\eta(P)} f(\lambda^{-\eta(P)}) \: d \lambda^{-\eta(P)}
\end{equation}

The definition of the density function is another Axiom... lognormal density....because it is a good approximation to the data and also for theoretical reasons that will now become clear...

Because yield is assumed to be lognormally distributed, then so is $\lambda$; and the Lemma given in the Appendix applies, giving
<!-- Since $\ln(\lambda)$ is normally distributed with mean $m_{\lambda}$ and variance $s_{\lambda}^2$, then $\ln(\lambda^{-\eta})$ is also normally distributed with mean $-\eta m_{\lambda}$ and variance $\eta^2 s_{\lambda}^2$. Since $\ln(\lambda^{-\eta})$ is normally distributed, $\lambda^{-\eta}$ may be substituted for $u$, such that $m_u = -\eta m_{\lambda}$, $s_u^2 = \eta^2 s_{\lambda}^2$, and $\bar{u} = h^{-\eta}$, giving the following expression. -->

\begin{equation}
\int_0^{h^{-\eta}} \lambda^{-\eta} f(\lambda^{-\eta}) \: d \lambda^{-\eta} = E[\lambda^{-\eta}] \Phi \left(\frac{\ln \left(\frac{h^{-\eta}}{E[\lambda^{-\eta}]} \right) - \eta^2 \frac{s_{\lambda}^2}{2}}{\eta s_{\lambda}} \right)
\label{eq:phiLambda}
\end{equation}

Where $m_{\lambda} = E[\ln(\lambda)]$ and $s_{\lambda}^2 = Var[\ln(\lambda)]$.

But recall that $\lambda = h E[b(T)]\bigr|_{t = 0}$; and so

\begin{equation}
s_{\lambda}^2 = Var[\ln(E[b(T)]\bigr|_{t = 0})]
\end{equation}

\begin{equation}
E[\lambda] = h E[E[b(T)]\bigr|_{t = 0}]
\end{equation}

And note that, by Rubini's theorem,

\begin{equation}
E[E[b(T)]\bigr|_{t = 0}] = E[E[b(T)]]\bigr|_{t = 0}
\end{equation}

Or, introducing the more compact notation $\mu_b(T) = E[b(T)]$,

\begin{equation}
E[E[b(T)]\bigr|_{t = 0}] = E[\mu_b(T)]\bigr|_{t = 0} \end{equation}
\end{equation}

That is, the population mean of the expected value of $b(T)$ is equal to the expected value of the population mean of $b(T)$.

Likewise,

\begin{equation}
s_{\lambda}^2 = Var[\ln(\mu_b(T))]\bigr|_{t = 0}
\end{equation}

Moreover, assuming $b(t)$ follows a geometric Brownian motion, then

\begin{equation}
\begin{split}
E[\mu_b(T)]\bigr|_{t = 0} &= \mu_b(0) e^{m_{\mu} T} \\
Var[\ln(\mu_b(T))]\bigr|_{t = 0} &= s_{\mu}^2 T
\end{split}
\end{equation}

Where 

\begin{equation}
\begin{split}
m_{\mu} &= E\left[\frac{\Delta \mu(T)}{\mu(T) \Delta t} \right] \\
s_{\mu}^2 &= Var\left[\frac{\Delta \mu(T)}{\mu(T) \Delta t} \right]
\end{split}
\end{equation}

For an instantaneous (in practice, judiciously small) time step $\Delta t$. (For a full introduction to geometric Brownian motion, see Hull [-@].) Therefore, $E[\lambda]$ may be expressed

\begin{equation}
\begin{split}
E[\lambda] &= h E[\mu_b(T)]\bigr|_{t = 0} \\
&= h \mu_b(0) e^{m_{\mu} T}
\end{split}
\end{equation}

And $E[\lambda^{-\eta}]$ may be expressed

\begin{equation}
\begin{split}
E[\lambda^{-\eta}] &= (h E[\mu_b(T)]\bigr|_{t = 0})^{-\eta} \\
&= h^{-\eta} \mu_b(0)^{-\eta} e^{-\eta m_{\mu} T}
\end{split}
\end{equation}

Substituting this into equation \ref{eq:phiLambda} gives

\begin{equation}
\begin{split}
\int_0^{h^{-\eta}} \lambda^{-\eta} f(\lambda^{-\eta}) \: d \lambda^{-\eta} &= h^{-\eta} \mu_b(0)^{-\eta} e^{-\eta m_{\mu} T} \Phi \left(\frac{\ln (\mu_b(0)^{\eta}) + \eta m_{\mu}T - \eta^2 \frac{s_{\mu}^2}{2}T}{\eta s_{\mu} \sqrt{T}} \right) \\
&= h^{-\eta} \mu_b(0)^{-\eta} e^{-\eta m_{\mu} T} \Phi \left(- \frac{\ln (\mu_b(0)^{-\eta}) - \left(\eta m_{\mu} - \eta^2 \frac{s_{\mu}^2}{2} \right) T}{\eta s_{\mu} \sqrt{T}} \right)
\end{split}
\end{equation}

Or, more compactly,

\begin{equation}
h^{-\eta} \mu_b(0)^{-\eta} e^{-\eta m_{\mu} T}(1 - \Phi(z))
\label{eq:termFinal}
\end{equation}

Where

\begin{equation}
z = \frac{\ln (\mu_b(0)^{-\eta}) - \left(\eta m_{\mu} - \eta^2 \frac{s_{\mu}^2}{2} \right) T}{\eta s_{\mu} \sqrt{T}}
\end{equation}

is the standard score of $\eta \ln(\mu_b(T)/\mu_b(0))$ evaluated at $\mu_b(T) = 1$. $\Phi(z)$ is therefore the probability that the population mean of the farm marginal revenue to cost ratio---i.e. $\mu_b(0)$---will fall below $1$ by the time of harvest and sale. It follows, then, that $1 - \Phi(z)$ is the probability that the mean farm marginal revenue to cost ratio will remain greater than $1$ by the time of sale.

\begin{equation}
\begin{split}
1 - \Phi(z) &= \text{Prob}(\mu_b(T) > 1) \\
&= \text{Prob}( P(T) > \mu_{\tilde{C}}(T)) \:\:;\:\:\: \mu_{\tilde{C}} = E[\tilde{C}]
\end{split}
\end{equation}

By Axiom 2(?), $b(0) > 1$ on all farms. The bet a farmer makes ex-ante is that $b(T) > 1$. The term $1 - \Phi(z)$ is a measure of the riskiness of this bet.

Substituting equation \ref{eq:termFinal} in for the integral in equation \ref{eq:QSeq} then gives the final form of the aggregate supply curve.

\begin{equation}
E[Q_S(T)]\bigr|_{t = 0} = N_f y_0^{\theta} E[\hat{\beta}^{\theta}] E[P(T)]\bigr|_{t = 0}^{\eta} h^{-\eta} \mu_b(0)^{-\eta} e^{-\eta m_{\mu} T}(1 - \Phi(z))
\label{eq:QSFin}
\end{equation}

(E[P(T)]\bigr|_{t = 0} = P(0)e^{m_P T})

and so participation is proportional to the risk of the bet


...repeat for the cost form of yield













\begin{equation}
\int_{0}^{h^{-\eta(P)}} \lambda^{-\eta(P)} f(\lambda^{-\eta(P)}) \: d \lambda^{-\eta(P)} = E[\lambda^{-\eta(P)}] (1 - \Phi(z))
\end{equation}

Where

\begin{equation}
z = \frac{\ln\left( \left( \frac{\mu_{\tilde{C}}(0)}{P(0)} \right)^{\eta(D)} \right) - \left(\eta(D) m_{\lambda} - \eta(D)^2 \frac{s_{\lambda}^2}{2} \right)T}{s_{\lambda} \sqrt{T}}
\end{equation}

The term $1 - \Phi(z)$ may thus be interpreted as the probability, at planting time, that the elasticity adjusted output price at time of harvest and sale $P(T)^{\eta(P)}$ will be greater than the corresponding elasticity adjusted mean marginal cost of production $\mu_{\tilde{C}}(T)^{\eta(D)}$.

\begin{equation}
1 - \Phi(z) = \text{Prob}(P(T)^{\eta(D)} > \mu_{\tilde{C}}(T)^{\eta(D)})
\end{equation}

There are two sources of uncertainty. Price risk ...Marginal cost of production is a function of input quantities purchased, input prices, and yield. Input prices and quantities are not a source of risk here as all major expenditures have been made and are known by the time of planting, when the evaluation is made. This leaves agroclimatic risk surrounding yield as the major source of uncertainty surrounding the ultimate value of marginal cost of production.
<!-- The effect of $\eta(D)$ in this equation is to regulate the rate at which the condition $P(T)^{\eta(D)} > \mu_{\tilde{C}}(T)^{\eta(D)}$ is met (or fails) with changes in either $P(T)$ or $\mu_{\tilde{C}}(T)$. To see this, it may be helpful to rewrite the condition in terms of a "marginal benefit-cost" ratio $r$. -->
<!-- \begin{equation} -->
<!-- 1 - \Phi(z) = \text{Prob}(r^{\eta(D)} > 1) \:\:;\:\:\: r = P(T) / \mu_{\tilde{C}}(T) -->
<!-- \end{equation} -->
<!-- As $\eta(D)$ is lower, $r^{\eta(D)}$ changes less when $r$ changes. As $\eta(D)$ is higher, movements of $r^{\eta(D)}$ become more pronounced in response to changes in $r$. -->

# Discussion

In defense of CobbDoug
[Mention the good empirical fit and validation tests (input demand, optimal area, etc.) as arguments in favor of C-D]

Translog is so "flexible" that it ends up being restrictive from an economic standpoint---not homogeneous, monotonicity and concavity, global concavity requires negative semidefinite matrix of parameters, enforcement of which "destroys the flexibility of the form" and restricts the price elasticities in undesired way (from "Estimating a Derived Demand System from a Translog Cost Function"). Jorgenson etc. have to then devise ways to make it less flexible, in order to impose constant returns to scale, for eg.

However, it does not directly address---not in an obvious way---the most enduring objections to the form: its perceived conflict with evidence and intuitions regarding 1) input substitution, 2) production elasticities, and 3) factor demand elasticities. A complete response to these objections is beyond the scope of the work at hand. Nonetheless, a minimal response is sketched out below in the hopes of retaining the attention of the many vigorous critics of Cobb-Douglas who might otherwise read no further.

Enduring objection 1 is that the Cobb-Douglas function implies a unitary elasticity of input substitution, whereas intuition and evidence clearly suggest otherwise. Arrow et al. [-@arrow1961capital] set the tone in their seminal article:

>"Technological alternatives are numerous and flexible in some sectors, limited in others; and uniform substitutability is most unlikely. The difference in elasticities is confirmed by direct observation of capital-labor proportions, which show much more variation among countries in some sectors than in others".

However, the authors here are objecting not to unitary elasticity of substitution, but rather "uniform substitutability". The measure of substitutability of one input for another in a two factor model $y(x_1, x_2)$ given an output target is not the elasticity of substitution, but rather the marginal rate of substitution, $dx_1/dx_2$. And the phrase "uniform substitutability" followed closely by the word "elasticities" may reasonably be interpreted as $d\ln(x_1)/\ln(dx_2) = 1$. (Hundreds of subsequent authors espousing this objection appear to mean this, at any rate.) It is straightforward to show that the two factor Cobb-Douglas model does not imply this. On the contrary, it implies

\begin{equation}
\frac{d \ln(x_1)}{d\ln(x_2)} = -\frac{\alpha_2}{\alpha_1}
\end{equation}

And thus agrees with Arrow et al.'s observations regarding the unlikelihood of "uniform substitutability".

At the same time, it is true that the two factor Cobb-Douglas model implies a unitary elasticity of substitution. But the elasticity of substitution is not a measure of factor substitutability. It is a measure of how factor proportions change with substitutability. A unitary elasticity of substitution thus means that a $1\%$ change in substitutability ($dx_1/dx_2$) results in a $1\%$ change in the ratio $x_1/x_2$. In plain English: a change in substitutability of $x_1$ for $x_2$ results in a proportionate change in the substitution of $x_1$ for $x_2$. One may conjecture without controversy that most farm managers would consider this an eminently reasonable characterization of management decision-making.

Enduring objection 2 is that the Cobb-Douglas production elasticities $\alpha_i$ are constant, whereas intuition suggests that production elasticities are functions of inputs, and should thus vary with input use. To lift this "restriction", the translog production function was introduced, with production elasticities defined as Cobb-Douglas functions of the inputs.

While the Cobb-Douglas production elasticities are indeed constant, it is fallacious to then conclude from this that they are not functions of the inputs. On the contrary, by Euler's theorem it is straightforward to show that

\begin{equation}
\alpha_i = \left(\frac{h - 1}{h} \right)  \frac{x_i}{y} \sum_{j}^{n} \frac{\partial^2 y}{\partial x_i \partial x_j} x_j
\end{equation}

And, moreover,

\begin{equation}
\frac{\partial^2 y}{\partial x_i \partial x_j} = \frac{1}{h - 2}  \sum_{k}^{n} \frac{\partial}{ \partial x_i} \frac{\partial y}{\partial x_j \partial x_k} x_k
\end{equation}

And, so on for any order $\mathcal{\ell}}$ of differentiation, ad infinitum,

\begin{equation}
\frac{\partial^{\ell} y}{\partial x_i^{\ell}} = \frac{1}{h - \ell + 1}  \sum_{j}^{n} \frac{\partial^{\ell + 1} y}{\partial x_i^{\ell + 1} \partial x_j} x_j
\end{equation}

That is to say, for $h \neq 1$, the Cobb-Douglas production elasticities are not just functions of all inputs, but also of the $2^{nd}$, $3^{rd}$, $\dots$,$\infty^{th}$ order variation of production with respect to inputs, as well as the interactions of these implied in the successive orders of cross derivatives. That all this complex interaction should add up to a constant is a sign not of oversimplification, then, but of mathematical serendipity stemming from Axiom 1. The translog function, meanwhile, is not derived from any first principle and is not even a homogeneous function. Which, then, is the more restrictive model?

It may be added that the economic principle of net-benefit maximization (cost minimization) implies that optimal input quantities are functions of prices and control variables, and are thus constant. In this sense, the translog production elasticities are also constant.

The same riposte applies to enduring objection 3, namely, that the Cobb-Douglas input demand elasticities are constant, whereas intuition and evidence indicate that input demand elasticities vary with input use. Again, it is true that Cobb-Douglas demand elasticities are constant. But, again, this does not mean that they are not functions of inputs. On the assumption that producers maximize their net benefit (or minimize cost), the Cobb-Douglas input demand own and cross price elasticities follows as

\begin{equation}

\end{equation}

The input own and cross price demand elasticities are thus functions of price and technology. Because optimal input use is also a function of price, these elasticities may be written as functions of input use, if so desired. Conversely, the Hicks-Allen partial elasticities derived using the translog model may be written in terms of prices, if so desired.

how to implement in minimum data contexts...

Also agrees with Lipton...

Lipton says... .

>\singlespacing "New science usually raises farm supply of outputs and demand for inputs. That makes outputs cheaper and inputs more expensive; hence the ratio of farm output prices to input prices falls. Do small and poor farmers gain? If, and only if, this science-induced fall in their relative farm prices is slower than the science-induced rise in their conversion ratio of physical inputs into physical outputs (that is, TFP)" [-@lipton2005family].

the mapping defaults to the subjective preferences of the modeler, which in turn prefigures the results of the impact assessment.  ...arbitrarily set by modeler...in the name of expedience, then, petitio principii. an assumed result dressed up in mathematical symbols. [In lit review: The most famous example is whether an improved variety does a shift or pivot of the supply curve. Results depend critically on this choice...conflict of interest.] Counterveiling changes in prices...Lipton.

in Discussion: the starting Axioms are to be experimented with. Other sets of Axioms might yield the same or different results.

...the numerous methodological headaches incurred in the pursuit of expedience, outlined above (and reviewed in more detail below), outweigh any gain in computational expedience. [What good is computational expedience if it is not even clear what is being calculated, what its connection to reality is]

can also address questions of how the same result might be achieved through interventions of other variables (Ethiopia bean an example), so as to compare which impact pathway is cheapest


sketch out extension to aggregate demand and PE analysis


# References {-}

<div id="refs"></div>

\pagebreak

# Appendix

Proof of equation ...

Given a lognormally distributed random variable $u$, such that $\ln(u)$ is normally distributed with mean $m_u$ and variance $s_u^2$, then the expected value of $u$ is
<!-- Where $p(q)$ is the probability density function of the random variable $q$. If $\ln(q)$ is normally distributed with mean $m_u$ and variance $s_u^2$, then -->

\begin{equation}
E[u] = e^{m_u + \frac{s_u^2}{2}}
\label{eq:muU}
\end{equation}

And the probability density function of $u$ is

\begin{equation}
f(u) = \frac{1}{u s_u} \phi \left(\frac{\ln(u) - m_u}{s_u} \right)
\end{equation}

Where $\phi()$ is the standard normal probability density function.

Now, introducing a change of variables,

\begin{equation}
p = \frac{\ln(u) - m_u}{s_u}
\label{eq:subThis1}
\end{equation}

Such that

\begin{equation}
\frac{dp}{du} = \frac{1}{u s_u}\: \rightarrow \: d u = u s_u dp
\label{eq:subThis2}
\end{equation}

Then

\begin{equation}
\begin{split}
\int_0^{\bar{u}} u f(u) \: du &= \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{s_u p + m_u} \phi(p) \: dp  \\
&= \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{s_u p + m_u} \frac{1}{\sqrt{2 \pi}} e^{\frac{p^2}{2}} \: dp \\
&= \frac{1}{\sqrt{2 \pi}} \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{p s_u + m_u -\frac{p^2}{2}} \: dp \\
&= \frac{1}{\sqrt{2 \pi}} \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{-1 / 2 (p^2 - 2 p s_u - 2 m_u)} \: dp \\
&= \frac{1}{\sqrt{2 \pi}} \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{-\frac{(p - s_u)^2}{2} + m_u + \frac{s_u^2}{2}} \: dp \\
&= \frac{1}{\sqrt{2 \pi}} \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{-\frac{(p - s_u)^2}{2}} e^{m_u + \frac{s_u^2}{2}} \: dp \\
&= e^{m_u + \frac{s_u^2}{2}} \frac{1}{\sqrt{2 \pi}} \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{-\frac{(p - s_u)^2}{2}} \: dp \\
&= \frac{E[u]}{\sqrt{2 \pi}} \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} e^{-\frac{(p - s_u)^2}{2}} \: dp \\
&= \frac{E[u]} \int_0^{\frac{\ln(\bar{u}) - m_u}{s_u}} \phi(p - s_u) \: dp \\
&= \frac{E[u]} \Phi \left(\frac{\ln(\bar{u}) - m_u}{s_u} - s_u \right)
\end{split}
\end{equation}

Finally, rearranging equation \ref{eq:muU} into an expression for $m_u$

\begin{equation}
m_u = \ln(E[u]) - \frac{s_u^2}{2}
\end{equation}

And substituting this in for $m_u$ in the previous expression gives

\begin{equation}
\begin{split}
\int_0^{\bar{u}} u f(u) \: du &= \frac{E[u]} \Phi \left(\frac{\ln(\bar{u}) - \ln(E[u]) + \frac{s_u^2}{2} }{s_u} - s_u \right) \\
&= \frac{E[u]} \Phi \left(\frac{\ln \left(\frac{\bar{u}}{E[u]} \right) - \frac{s_u^2}{2} }{s_u} \right)
\end{split}
\end{equation}

\blacksquare





<!-- <!-- this can be rewritten --> -->
<!-- <!-- \begin{equation} --> -->
<!-- <!-- \int_0^{h^{-\theta}} \lambda^{-\theta} f(\lambda^{-\theta}) \: d \lambda^{-\theta} = h^{-\theta} E[E[b(T)]\bigr|_{t = 0}] \Phi \left(\frac{\ln \left(\frac{1}{E[E[b(T)]\bigr|_{t = 0}^{-\theta}]} \right) - \theta^2 \frac{\omega^2}{2}}{\theta \omega} \right) --> -->
<!-- <!-- \label{eq:refEq} --> -->
<!-- <!-- \end{equation} --> -->
<!-- <!-- Where $\omega^2 = Var[\ln(E[b(T)]\bigr|_{t = 0})]$. --> -->


<!--  Equation \ref{eq:refEq} may now be rewritten -->

<!-- \begin{equation} -->
<!-- \begin{split} -->
<!-- \int_0^{h^{-\theta}} \lambda^{-\theta} f(\lambda^{-\theta}) \: d \lambda^{-\theta} &= h^{-\theta} E[\mu_b(T)^{-\theta}]\bigr|_{t = 0} \Phi \left(\frac{\ln \left(\frac{1}{E[\mu_b(T)]\bigr|_{t = 0}^{-\theta}} \right) - \theta^2 \frac{s_{\mu}^2}{2} T}{\theta s_{\mu} T} \right) \\ -->
<!-- &= h^{-\theta} \mu_b(0)^{-\theta} e^{-\theta m_{\mu} T} \Phi \left(\frac{\ln \left(\frac{1}{\mu_b(0)^{-\theta}} \right) - \theta m_{\mu}T - \theta^2 \frac{s_{\mu}^2}{2} T}{\theta s_{\mu} T} \right) \\ -->
<!-- &= h^{-\theta} \mu_b(0)^{-\theta} e^{-\theta m_{\mu} T} \Phi \left( -\frac{\ln \left(\frac{1}{\mu_b(0)^{-\theta}} \right) - \left(\theta m_{\mu} - \theta^2 \frac{s_{\mu}^2}{2}\right) T}{\theta s_{\mu} T} \right) -->
<!-- \end{split} -->
<!-- \end{equation} -->




<!-- The mean and variance of the log fractional change (or "return") of $\mu_b(t)$ over period $T$, meanwhile, are -->

<!-- \begin{equation} -->
<!-- \begin{split} -->
<!-- E \left[ \ln \left( \frac{\mu_b(T)}{\mu_b(0)} \right) \right] &= \left(m_{\mu} - \frac{s_{Eb}^2}{2} \right) T \\ -->
<!-- Var \left[ \ln \left( \frac{\mu_b(T)}{\mu_b(0)} \right) \right] &= Var[\ln(\mu_b(T))]\bigr|_{t = 0} = s_{\mu}^2 T -->
<!-- \end{split} -->
<!-- \end{equation} -->

<!-- By which it follows that the -->


